### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by xiejun** [blackstar-baba/how-2-use-thingsboard#1]
请问下这个报错怎么解决？
<img width="1788" alt="image" src="https://user-images.githubusercontent.com/1418991/118061845-5b358f80-b3c8-11eb-863a-a2fe1c586651.png">

**Comment by xiejun** [comment]
重新下载了下，又报这个错误
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/1418991/118065120-047f8400-b3cf-11eb-92f6-5630c8a00c9e.png">

**Comment by xiejun** [comment]
解决了，只能用java 8，不能用java 11，阿里的Maven源必须配置在/Users/xxx/lib/apache-maven-3.6.3/conf/settings.xml里

**Comment by blackstar-baba** [comment]
如果拉分支release-3.2最新代码，编译环境是需要jdk11的

**Comment by Lu-fk** [comment]
相同的错误，无论1.8还是11都会遇到。请问是如何解决的? 与maven镜像有关吗

**Comment by blackstar-baba** [comment]
> 相同的错误，无论1.8还是11都会遇到。请问是如何解决的? 与maven镜像有关吗

参考下这个：https://github.com/blackstar-baba/how-2-use-thingsboard/blob/main/doc/%E7%BC%96%E8%AF%91/%E7%BC%96%E8%AF%91.md
