### ISSUE TITLE
Mac环境可以源码安装吗

### ISSUE THREAD

**Issue by serapme** [blackstar-baba/how-2-use-thingsboard#2]
执行到yarn install报错

源码 mvn clean install -Ddockerfile.skip=false -DskipTests=true
[INFO] Running 'yarn install' in /Users/derek/thingsboard/msa/js-executor
[INFO] yarn install v1.22.4
[INFO] [1/5] Validating package.json...
[INFO] [2/5] Resolving packages...
[INFO] success Already up-to-date.
[INFO] $ pkg -t node12-linux-x64,node12-win-x64 --out-path ./target . && node install.js
[INFO] > pkg@4.4.9
[INFO] > Warning Failed to make bytecode node12-x64 for file /snapshot/js-executor/server.js error (write EPIPE)
[ERROR] events.js:288
[ERROR]       throw er; // Unhandled 'error' event
[ERROR]       ^
[ERROR] 
[ERROR] Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
[ERROR]     at doWrite (_stream_writable.js:437:19)
[ERROR]     at writeOrBuffer (_stream_writable.js:425:5)
[ERROR]     at Socket.Writable.write (_stream_writable.js:316:11)
[ERROR]     at fabricate (/Users/derek/thingsboard/msa/js-executor/node_modules/pkg/lib-es5/fabricator.js:131:15)
[ERROR]     at /Users/derek/thingsboard/msa/js-executor/node_modules/pkg/lib-es5/fabricator.js:144:23
[ERROR]     at Socket.onError (/Users/derek/thingsboard/msa/js-executor/node_modules/pkg/lib-es5/fabricator.js:83:5)
[ERROR]     at Socket.emit (events.js:311:20)
[ERROR]     at errorOrDestroy (internal/streams/destroy.js:108:12)
[ERROR]     at onwriteError (_stream_writable.js:456:5)
[ERROR]     at onwrite (_stream_writable.js:483:5)
[ERROR] Emitted 'error' event on Socket instance at:
[ERROR]     at errorOrDestroy (internal/streams/destroy.js:108:12)
[ERROR]     at onwriteError (_stream_writable.js:456:5)
[ERROR]     at onwrite (_stream_writable.js:483:5)
[ERROR]     at doWrite (_stream_writable.js:437:11)
[ERROR]     at writeOrBuffer (_stream_writable.js:425:5)
[ERROR]     [... lines matching original stack trace ...]
[ERROR]     at Socket.emit (events.js:311:20) {
[ERROR]   code: 'ERR_STREAM_DESTROYED'
[ERROR] }
[ERROR] error Command failed with exit code 1.
[INFO] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by blackstar-baba** [comment]
我本人的电脑就是MAC，能否贴一些更详细的信息，比如编译环境、TB版本、网络是否有代理和详细的日志

**Comment by serapme** [comment]
> 我本人的电脑就是MAC，能否贴一些更详细的信息，比如编译环境、TB版本、网络是否有代理和详细的日志

好的 知道mac能做我就再尝试下。
我当前环境 
mac 
处理器Intel I7
 java 11.0.12
code :release 3.2
网络没有代理（代理有区别吗）maven npm全部设置的淘宝阿里源
详细日志就是主贴贴的 Warning Failed to make bytecode node12-x64 for file /snapshot/js-executor/server.js error (write EPIPE)
