### ISSUE TITLE
规则节点二次开发报错

### ISSUE THREAD

**Issue by freebooterish** [blackstar-baba/how-2-use-thingsboard#4]
您好！
我在做规则节点二次开发尝试，按照文档 Clone [git@github.com:blackstar-baba/rule-node-examples-ui-ngx.git](url)并切换到customer后，执行到 yarn run build 时报以下错误，官网的rule-node-examples-ui-ngx前几天也报同样错误，不过昨天修正了，您能否给些提示？非常感谢您的无私奉献！
yarn run v1.22.17
$ ng build && node install.js
Building Angular Package

------------------------------------------------------------------------------
Building entry point 'custom-nodes-config'
------------------------------------------------------------------------------
Compiling TypeScript sources through ngc
ERROR: Undefined function.
56 │     $x1: $x0 - math.div($x0 * $x0 - abs($r), 2 * $x0);
   │                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  node_modules/thingsboard/src/scss/mixins.scss 56:16                               sqrt()
  node_modules/thingsboard/src/app/shared/components/popover.component.scss 123:12  root stylesheet
See "/private/var/folders/0h/f6rx0q794js8q_0rtffvs8l80000gn/T/ng-V8oYuV/angular-errors.log" for further details.
error Command failed with exit code 127.

**Comment by blackstar-baba** [comment]
很抱歉，具体错误我也没看太明白，我对前端并不是特别熟悉，但有两点提示：
-   rule-node-examples-ui-ngx.git 对thingsboard工程主干代码有依赖，如果主干代码有更新，可能会影响编译
-  我分支上代码已合并到官方主干 https://github.com/thingsboard/rule-node-examples-ui-ngx/pull/24，后续可以尝试使用官方最新进行编译

**Comment by freebooterish** [comment]
> 很抱歉，具体错误我也没看太明白，我对前端并不是特别熟悉，但有两点提示：
> 
> * rule-node-examples-ui-ngx.git 对thingsboard工程主干代码有依赖，如果主干代码有更新，可能会影响编译
> * 我分支上代码已合并到官方主干 [https://github.com/thingsboard/rule-node-examples-ui-ngx/pull/24，后续可以尝试使用官方最新进行编译](https://github.com/thingsboard/rule-node-examples-ui-ngx/pull/24%EF%BC%8C%E5%90%8E%E7%BB%AD%E5%8F%AF%E4%BB%A5%E5%B0%9D%E8%AF%95%E4%BD%BF%E7%94%A8%E5%AE%98%E6%96%B9%E6%9C%80%E6%96%B0%E8%BF%9B%E8%A1%8C%E7%BC%96%E8%AF%91)

非常感谢您的回复！已经看到您的分支合并到官网，我再试试。

**Comment by freebooterish** [comment]
您好！
我按照文档做规则节点的二次开发输入链接说明，在没有UI的情况下一切正常，有UI时报错：无法加载UI资源，按照TIPS：如果遇到UI加载异常，可以删除数据库表omponent_descriptor关于··TbSystemCommandNode的一行记录，然后重启程序。依然报错，能给些提示吗？谢谢！
另外文档中：configDirective = "tbActionNodeSystemCommandConfig",//指定前端资源文件中的组件
configDirective是什么含义，官网中也不是太明确，没找到tbActionNodeSystemCommandConfig在哪里定义？能解答一下吗？多谢！

**Comment by ghost** [comment]
> 您好！ 我按照文档做规则节点的二次开发输入链接说明，在没有UI的情况下一切正常，有UI时报错：无法加载UI资源，按照TIPS：如果遇到UI加载异常，可以删除数据库表omponent_descriptor关于··TbSystemCommandNode的一行记录，然后重启程序。依然报错，能给些提示吗？谢谢！ 另外文档中：configDirective = "tbActionNodeSystemCommandConfig",//指定前端资源文件中的组件 configDirective是什么含义，官网中也不是太明确，没找到tbActionNodeSystemCommandConfig在哪里定义？能解答一下吗？多谢！

java：tbActionNodeSystemCommandConfig
在 rule-node-examples-ui-ngx 项目下面需要有一个模板（对应一个 ts 和 html），其中 ts 文件中的  selector="tb-action-node-system-command-config"

**Comment by freebooterish** [comment]
> java：tbActionNodeSystemCommandConfig
> 在 rule-node-examples-ui-ngx 项目下面需要有一个模板（对应一个 ts 和 html），其中 ts 文件中的 selector="tb-action-node-system-command-config"

谢谢您！
