### ISSUE TITLE
腦圖失效了

### ISSUE THREAD

**Issue by codeHui** [blackstar-baba/how-2-use-thingsboard#6]
https://github.com/blackstar-baba/how-2-use-thingsboard/blob/main/file/%E8%A7%92%E8%89%B2%E5%8A%9F%E8%83%BD%E8%84%91%E5%9B%BE.xmind
沒了

**Comment by blackstar-baba** [comment]
看着还在：https://github.com/blackstar-baba/how-2-use-thingsboard/blob/main/file/xmind/角色功能脑图.xmind

**Comment by blackstar-baba** [comment]
脑图文件根目录：https://github.com/blackstar-baba/how-2-use-thingsboard/tree/main/file/xmind
