### ISSUE TITLE
测试遥测数据

### ISSUE THREAD

**Issue by 1043021051** [blackstar-baba/how-2-use-thingsboard#7]
怎么连接MQTT.fx到http://blackstar-baba.com:9090/devices，想试试遥测数据
![image](https://user-images.githubusercontent.com/39759644/228116516-43bf39a1-19dc-4401-a8ef-479416219c1b.png)

**Comment by blackstar-baba** [comment]
look this: https://github.com/blackstar-baba/how-2-use-thingsboard/blob/main/doc/%E4%BD%BF%E7%94%A8/%E6%99%AE%E9%80%9A%E8%AE%BE%E5%A4%87.md

**Comment by 1043021051** [comment]
我想连接你的MQTT地址，Host需要填写什么？

**Comment by blackstar-baba** [comment]
Mqtt server port is 1883
