### ISSUE TITLE
想问一下大佬关于3D组件拓展的问题

### ISSUE THREAD

**Issue by hhhuskytc** [blackstar-baba/how-2-use-thingsboard#8]
我在按照您写的文档创建组件时，程序报了两处错误，我不太清楚是哪里的问题
但是好像是babylonjs的库并没有引用成功，因为报错的部位是babylonjs的库函数部位
我安装了npm，也安装了yarn，并且yarn是在全局下安装的，Thingsboard的环境是ubuntu
![QQ截图20230404170655](https://user-images.githubusercontent.com/121287993/229744271-0418eebf-c92e-49f9-a1e1-e3cad903563e.png)

**Comment by blackstar-baba** [comment]
You can look this commit: https://github.com/CodeIsBeatiful/thingsboard/commit/f4c14708082eff8fa6d45c1fd9ab96f9064ed1ef

**Comment by hhhuskytc** [comment]
> You can look this commit: [CodeIsBeatiful/thingsboard@f4c1470](https://github.com/CodeIsBeatiful/thingsboard/commit/f4c14708082eff8fa6d45c1fd9ab96f9064ed1ef)

已经使用第一种方式成功添加了3D组件，但还是谢谢您的回复
